### ISSUE TITLE
Create executable version of rushti

### ISSUE THREAD

**Issue by MariusWirtz** [cubewise-code/rushti#11]
Would be nice if rushti could be downloaded as a .exe file, so that it can be used in an environment without python.

**Comment by kool2zero** [comment]
I was able to do this using pyinstaller.  We use the exe without issue here:
**Install PyInstaller**
`pip install pyinstaller`

Create a spec file:
`
# -*- mode: python -*-

block_cipher = None

def get_pandas_path():
    import pandas
    pandas_path = pandas.__path__[0]
    return pandas_path

a = Analysis(['RushTI.py'],
             pathex=['E:\\_BIC_Custom\\Python_Scripts'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
dict_tree = Tree(get_pandas_path(), prefix='pandas', excludes=["*.pyc"])
a.datas += dict_tree
a.binaries = filter(lambda x: 'pandas' not in x[0], a.binaries)
																	
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='RushTI',
          debug=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True )
`
**Run the pyinstaller command **
`pyinstaller RushTI.spec --onefile`

It gets output in the ./build/RushTI/ directory.

**Comment by MariusWirtz** [comment]
This is awesome. Thank you!

I created a pre release with an executable version of RushTI attached. We will do some more testing internally, but it's looking good.
