### ISSUE TITLE
Error: 'ProcessService' object has no attribute 'execute_with_return'.

### ISSUE THREAD

**Issue by Etarasen** [cubewise-code/rushti#15]
Hi Mariuz,

Background: 

Running Python 3.6.7150.0

Due to restriction on a cloud server (cant download and use pip install TM1py), I had to paste TM1py package manually into ...\Python36\Libs.

I have tested Rest API connection to the server with check.py (in Tm1Py sampler). Connection successful

I have also confirmed with Postman with a simple GET

I have also confirmed by running a simple code from the samples, I get JSON feedback

Snippet from the Rush.txt:

2019-05-23 12:54:42,662 - RushTI - ERROR - Execution failed. Process: ProcessName: {'ParamOne': '1', 'ParaTwo': '1'}. Elapsed time: 0:00:00. Error: 'ProcessService' object has no attribute 'execute_with_return'.
2019-05-23 12:54:42,662 - RushTI - ERROR - RushTI ends. 1 fails out of 1 executions. Elapsed time: 0:00:00.015625

Please let me know what could be wrong here,

Evgeny

**Comment by MariusWirtz** [comment]
Hi,

It seems that your version of the TM1 Serrver does not have the `ExecuteWithReturn `method.

If you need a version of RushTI that is compatible with TM1 10.2.2 and the early versions of PA you can download the [release 0.1](https://github.com/cubewise-code/rushti/releases/tag/0.1.0)
It makes use of the old `Execute` method.

The only difference, in terms of functionality, is that the early release of RushTI expects your password in the config.ini file to be b64 encoded.

Cheers,

Marius

**Comment by Etarasen** [comment]
Thanks Marius, 

That helped indeed!

Regards,

Evgeny
