### ISSUE TITLE
RUSHTI.log file has no max capacity

### ISSUE THREAD

**Issue by lbrowncubewise** [cubewise-code/rushti#26]
It would be great if the RushTI.log file had a max capacity at which the file was recycled, similar to how tm1server.log is managed using the properties file, this would then enable effective management of the logging file, and when it hits a threashold the file would be set to log1 or similar up to a maximum threshold then purged? At the moment the logging file just gets bigger and bigger.

**Comment by MariusWirtz** [comment]
solved
https://github.com/cubewise-code/rushti/releases/tag/1.2.0
