### ISSUE TITLE
TIs which use ODBCOutput are not updating database correctly; missing records

### ISSUE THREAD

**Issue by the-bort-the** [cubewise-code/rushti#27]
When I run a normally scheduled chore (chore runs a 'control' TI which runs 5 TI processes), my 5 database tables (each TI updates a table) are updated with the correct information from the sourced cubes.
I can run and rerun the chore with the same results, same number of records in the tables.

When I run the rushti.py against the control TI, I see success in the processes, but my tables don't have the same amount of records; record counts are lower; sometimes a few hundred, sometimes thousands. 

Before I claim bug, I wish to know if I'm supplying the correct parameters to the rushti.py and using the ideal amount of cores/CPUs too. Currently I have 4 CPU, so I've been testing using 2 & 3.

**Comment by the-bort-the** [comment]
Focused in on 2 of the smaller tables ( < 1000 records & < 15,000 records) and they loaded fine. They don't have parameters, however. They just dump out two simple cubes and load to tables.

**Comment by MariusWirtz** [comment]
Hello @the-bort-the,

Did you look into the rushti log files? Can you find any Errors and Warnings there?
Could it be that the parameters are not passed through properly between RushTI and the executing TI?

**Comment by the-bort-the** [comment]
I will rerun a few more times. I want to ask, just for clarification on how the text file rushti is running at execution. Currently the control TI, running 5 additional TIs, is set to pass some parameters to the 2 of the 5 TIs. Is this possible?

Here is the basically architecture of the control TI and child TI. Control has parameters to run with 3 parameters (dimensions). Parameter 1 has 6 elements to update (1,2,3,4,5,6), while parameter 2 has only 1 element to update. Lastly, the third parameter has just 2 elements to update. I guess I'm wondering how I should be running this TI in rushti. Currently the control TI runs in TI with these parameters

Control TI ( Parameters: #1 (a,b,c,d,e,f), #2 (a), #3 (a,b) )
•	TI 1 ( Parameters: #1 (a,b,c,d,e,f), #2 (a), #3 (a,b) )
•	TI 2 ( Parameters: #1 (a,b,c,d,e,f), #2 (a), #3 (a,b) )
•	TI 3 ( Parameters: none)
•	TI 4 ( Parameters: none)
•	TI 5 ( Parameters: none)

Below is how I have been running the rushti from the Anaconda CLI:

> python .\RushTI.py .\dashboard.txt 2

The dashboard.txt file contains the parameters to run the control TI process as follows:

instance"TM1_INT" process"dashboard_tm1_control" pYear 2019
instance"TM1_INT" process"dashboard_tm1_control" pYear 2020

pYear is really paremters #3 in the above architecture of the control TI, where I need to run the control for both years. I'm hoping in this case, the other parameters will be run as required because they are listed in the child TIs themselves.

I think my overarching question is really, which parameters make sense to have in the child TI, which to have in the control TI, and which to have in the dashboard.txt being given to the rushti at runtime so I can take advantage of both CPUs. I feel like something is getting left out, or not executed. I don't seem to have errors in the TI; logs state every ran to success.

**Comment by MariusWirtz** [comment]
Hi @the-bort-the,

the first thing I notice is that you are missing the = signs in the txt file.
It needs to look like this:
```
instance="tm1srv01" process="}bedrock.server.wait" pWaitSec=1
wait
instance="tm1srv02" process="}bedrock.server.wait" pWaitSec=2
instance="tm1srv01" process="}bedrock.server.wait" pWaitSec=3
instance="tm1srv02" process="}bedrock.server.wait" pWaitSec=4
```

If possible I would execute everything through RushTI and avoid processes calling subprocesses. RushTI makes sure there are always n processes running at a time.
If there are dependencies between the processes you can add wait blocks in between the calls.

Regarding the CPU usage, If a process is calling a subprocess through ExecuteProcess, that process is running single-threaded.
So if your master process is calling 5 sub-processes through ExecuteProcess, they are executed sequentially.

I hope this helps.

Generally, we try to keep this forum for bugs and questions.
If you need more dedicated support for your use case, please get in touch with your local cubewise office.

Cheers,

Marius
