### ISSUE TITLE
[19088] Failed to execute script RushTI - error

### ISSUE THREAD

**Issue by mmastrolonardo** [cubewise-code/rushti#31]
Hello,

I am trying to use the executable version of RunTI, just donwloaded it today and there is no version indicated on the executable file properties. When launching a batch, it returns the following error:

_```
c:\python3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py:623: MatplotlibDeprecationWarning:
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
Traceback (most recent call last):
File "RushTI.py", line 471, in
tm1_service_by_instance
File "asyncio\base_events.py", line 579, in run_until_complete
File "RushTI.py", line 370, in work_through_tasks
outcomes.append(await future)
File "concurrent\futures\thread.py", line 57, in run
File "RushTI.py", line 298, in execute_line
task = extract_task_from_line(line)
File "RushTI.py", line 96, in extract_task_from_line
param, value = pair.split("=")
ValueError: not enough values to unpack (expected 2, got 1)
[19088] Failed to execute script RushTI
```_

I would be grald for any clue on how to solve this.

**Comment by MariusWirtz** [comment]
The tasks.txt file has to follow this pattern:

```
instance="tm1srv01" process="}bedrock.server.wait" pWaitSec=9
instance="tm1srv01" process="}bedrock.server.wait" pWaitSec=5
instance="tm1srv01" process="}bedrock.server.wait" pWaitSec=4
instance="tm1srv01" process="}bedrock.server.wait" pWaitSec=6
instance="tm1srv01" process="}bedrock.server.wait" pWaitSec=4
instance="tm1srv01" process="}bedrock.server.wait" pWaitSec=4
instance="tm1srv01" process="}bedrock.server.wait" pWaitSec=4
wait
instance="tm1srv01" process="}bedrock.server.wait" pWaitSec=9
instance="tm1srv01" process="}bedrock.server.wait" pWaitSec=5
instance="tm1srv01" process="}bedrock.server.wait" pWaitSec=4
instance="tm1srv01" process="}bedrock.server.wait" pWaitSec=4
instance="tm1srv01" process="}bedrock.server.wait" pWaitSec=6
instance="tm1srv01" process="}bedrock.server.wait" pWaitSec=4
instance="tm1srv01" process="}bedrock.server.wait" pWaitSec=4
wait
instance="tm1srv01" process="}bedrock.server.wait" pWaitSec=4
```

**Comment by mmastrolonardo** [comment]
Hi Marius,

this is the content oy tasks.txt file:

`instance="LAPP" process="APQ.C3.FIN.Cub.SalesData.Load.Step" pLogOutput=0 pYear=2017 pSrcFile=C:\TM1Models\LAPP\SourceData\Sales Data\SalesData_1400_2017.csv
instance="LAPP" process="APQ.C3.FIN.Cub.SalesData.Load.Step" pLogOutput=0 pYear=2017 pSrcFile=C:\TM1Models\LAPP\SourceData\Sales Data\SalesData_1500_2017.csv
instance="LAPP" process="APQ.C3.FIN.Cub.SalesData.Load.Step" pLogOutput=0 pYear=2017 pSrcFile=C:\TM1Models\LAPP\SourceData\Sales Data\SalesData_1600_2017.csv
instance="LAPP" process="APQ.C3.FIN.Cub.SalesData.Load.Step" pLogOutput=0 pYear=2017 pSrcFile=C:\TM1Models\LAPP\SourceData\Sales Data\SalesData_2100_2017.csv
instance="LAPP" process="APQ.C3.FIN.Cub.SalesData.Load.Step" pLogOutput=0 pYear=2017 pSrcFile=C:\TM1Models\LAPP\SourceData\Sales Data\SalesData_5100_2017_01.csv
instance="LAPP" process="APQ.C3.FIN.Cub.SalesData.Load.Step" pLogOutput=0 pYear=2017 pSrcFile=C:\TM1Models\LAPP\SourceData\Sales Data\SalesData_5100_2017_02.csv
instance="LAPP" process="APQ.C3.FIN.Cub.SalesData.Load.Step" pLogOutput=0 pYear=2017 pSrcFile=C:\TM1Models\LAPP\SourceData\Sales Data\SalesData_5100_2017_03.csv
instance="LAPP" process="APQ.C3.FIN.Cub.SalesData.Load.Step" pLogOutput=0 pYear=2017 pSrcFile=C:\TM1Models\LAPP\SourceData\Sales Data\SalesData_5100_2017_04.csv
instance="LAPP" process="APQ.C3.FIN.Cub.SalesData.Load.Step" pLogOutput=0 pYear=2017 pSrcFile=C:\TM1Models\LAPP\SourceData\Sales Data\SalesData_5100_2017_05.csv
instance="LAPP" process="APQ.C3.FIN.Cub.SalesData.Load.Step" pLogOutput=0 pYear=2017 pSrcFile=C:\TM1Models\LAPP\SourceData\Sales Data\SalesData_5100_2017_06.csv
instance="LAPP" process="APQ.C3.FIN.Cub.SalesData.Load.Step" pLogOutput=0 pYear=2017 pSrcFile=C:\TM1Models\LAPP\SourceData\Sales Data\SalesData_5100_2017_07.csv
instance="LAPP" process="APQ.C3.FIN.Cub.SalesData.Load.Step" pLogOutput=0 pYear=2017 pSrcFile=C:\TM1Models\LAPP\SourceData\Sales Data\SalesData_5100_2017_08.csv
instance="LAPP" process="APQ.C3.FIN.Cub.SalesData.Load.Step" pLogOutput=0 pYear=2017 pSrcFile=C:\TM1Models\LAPP\SourceData\Sales Data\SalesData_5100_2017_09.csv
instance="LAPP" process="APQ.C3.FIN.Cub.SalesData.Load.Step" pLogOutput=0 pYear=2017 pSrcFile=C:\TM1Models\LAPP\SourceData\Sales Data\SalesData_5100_2017_10.csv
instance="LAPP" process="APQ.C3.FIN.Cub.SalesData.Load.Step" pLogOutput=0 pYear=2017 pSrcFile=C:\TM1Models\LAPP\SourceData\Sales Data\SalesData_5100_2017_11.csv
instance="LAPP" process="APQ.C3.FIN.Cub.SalesData.Load.Step" pLogOutput=0 pYear=2017 pSrcFile=C:\TM1Models\LAPP\SourceData\Sales Data\SalesData_5100_2017_12.csv`

I have also tried with enclosing the parameter values in quotes..

**Comment by MariusWirtz** [comment]
One task must be in one line. You must not have linebreaks in a task. You can take my sample above as a reference.

**Comment by 4rtem** [comment]
Hi guys, some more things to check. I think string parameters must be in double-quotes. I see that at least for pSrcFile, not sure what is the type for pYear, pLogOutPut. I do not remember exactly, but empty lines in the file can be also the source of the problem.

**Comment by mmastrolonardo** [comment]
Hello,
I enclosed in double quotes the parameters having spaces in their values and all works now.
Thanks!
