### ISSUE TITLE
Windows network path like (\\host\prd\OPFP-PRD\TM1Applications\OPFP-PRD\Data\) cannot be passed as the parameter to TI through RushTi script

### ISSUE THREAD

**Issue by 4rtem** [cubewise-code/rushti#33]
The problem is related to shlex.split(line) which is decomposing backslash "\" symbol as ESC sequence.
I was able to resolve this only by replacing "\" by "/". As our script is generated via TI I needed to write a code replacing backslashes in TI code.

**Comment by MariusWirtz** [comment]
Hi @4rtem,

if you just escape every `\` with an additional `\` before you pass it to rushti, does it work?
is that an acceptable solution?

**Comment by 4rtem** [comment]
@MariusWirtz , I have tested, all works good in the updated script
