### ISSUE TITLE
It might be good if first line also takes "0" as the predecessors, currently the script will fail if we put "0"

### ISSUE THREAD

**Issue by 4rtem** [cubewise-code/rushti#35]
id="1" predecessors="" instance="One Plan GP" process="Sys.SaveWrapperStart" pStart=1

**Comment by MariusWirtz** [comment]
Now `""`, `"0"` and `0` is understood as 'no predecessor' https://github.com/cubewise-code/rushti/commit/c48f7b1329ad28f5f63735e731f5e1a550a31aee
