### ISSUE TITLE
How to execute processes with RushTI using CAM authentication?

### ISSUE THREAD

**Issue by rakhmatullinar** [cubewise-code/rushti#36]
Hi,

is there any way to execute processes with RushTI using CAM authentication?

**Comment by MariusWirtz** [comment]
Hi,

you need to adjust the config.ini accordingly.
https://code.cubewise.com/tm1py-help-content/how-to-authenticate-to-tm1-with-tm1py

**Comment by rakhmatullinar** [comment]
I tried to adjust config.ini file, but is doesn't work properly

If config.ini is adjusted like this everything works fine
![image](https://user-images.githubusercontent.com/81569231/113990422-1dd66300-985a-11eb-838f-9089b0ad6ddd.png)

When I try to adjust it to use CAM with SSO from the article above I get error "Process '#' not executed on 'tm1srv01'. 'tm1srv01' not accessible"
![image](https://user-images.githubusercontent.com/81569231/113993120-c5ed2b80-985c-11eb-850e-d83ba07d14fd.png)

**Comment by MariusWirtz** [comment]
for gateway provide the `ClientCAMURI` from the tm1s.cfg.
The namespace is case sensitive.

That should be it

**Comment by rakhmatullinar** [comment]
Yep, I provide ClientCAMURI for gateway
I thinke case-sensitivity of namespace is not the point, cause it works fine without gateway
Have tried different ways of typing gateway (e.g. with quotes or without) but the problem remains

Some additional info: Execution is made from TI with Executecommand and it works fine when I hardcode user/password ro config.ini

sCommand = 'python ' | sRushTI | ' ' | sTaskFile|  ' '|pNbThreads;
ExecuteCommand(sCommand,1);
