### ISSUE TITLE
Task Split incorrectly.

### ISSUE THREAD

**Issue by dfrankenCW** [cubewise-code/rushti#39]
HI there

I ran into a problem splitting my tasks correctly:

The task:

![image](https://user-images.githubusercontent.com/67896365/117412676-f3390200-af0c-11eb-9143-8c8eb7e4ba74.png)

Debugging RushTI I found (row 96):

![image](https://user-images.githubusercontent.com/67896365/117412756-0e0b7680-af0d-11eb-876f-0bcb2bab0502.png)

The split is being done by shlex.split() with the posix=False.  When set to True it parses the task correctly. (as seen above)

Thanks!

**Comment by MariusWirtz** [comment]
Hi @dfrankenCW,

That's on me. This week we shortly had this flaw in the master branch. If you download the latest master branch, `shlex.split` should have `posix` back to `True` (default value) https://github.com/cubewise-code/rushti/commit/57440709d18248bc0a2cfb7808f66abce9d239aa
