### ISSUE TITLE
Expand functionality of `retry` to not retry when process returns minor error

### ISSUE THREAD

**Issue by MateuszOszer** [cubewise-code/rushti#41]
HI, 

It would be convinient to be able to use the norm to repeat a TI if it failed, but only if it did not actually commit, rather then when it commited with minor errors. I would like to use this functionality, as my TIs randomly need to rerun, but due to the fact that I am using cellincrement I could potentially run into the issue where minor error (change of rule and now You have cell not updatable or something like this) would essentially double the values.

**Comment by MariusWirtz** [comment]
Thanks, @MateuszOszer. Will look into this!
