### ISSUE TITLE
Calling same TI that uses RushTI twice in a master processes causes WAIT deadlock

### ISSUE THREAD

**Issue by meyersrl** [cubewise-code/rushti#46]
I have a master archive process that uses RushTI to execute the slave process for each month copying from Version A to Version B.  Then turns off the Attribute we use to dynamically calculate FX and then copies back the data from Version B to Version A.  The idea is archive the data as a static version.

The issue is that when the second call of the archive TI occurs the RushTI processes all go into wait mode for the master process which creates a deadlock and I have to manually kill the master process.

Is this a known issue that needs to be worked around?  If so then what is the best approach to call a sub processes twice that uses RushTI?

**Comment by MariusWirtz** [comment]
Hi @meyersrl,
sorry for the late response.

Were you able to resolve the issue outside of RushTI?
Is there anything we can do in the RushTI logic to help you resolve the locking issue? If so, please re-open the issue
