### ISSUE TITLE
tm1srv01 not accessible

### ISSUE THREAD

**Issue by mandeepSin** [cubewise-code/rushti#48]
Hi I am receiving the following error message, however when the same command is ran from command line RushTi it works, but when called from a TI process we get the following message. 

 RushTI - ERROR - TM1 instance tm1srv01 not accessible. Error: Failed to authenticate through CAM. HTTP response does not contain 'cam_passport' cookie

**Comment by MariusWirtz** [comment]
Could it be that the user that runs the TM1 Service (Windows Service) doesn't have permission to access TM1?

**Comment by mandeepSin** [comment]
Hi Marius, thanks for your reply, the TM1 account is a admin in windows and in TM1.

**Comment by MariusWirtz** [comment]
I can't say for sure without looking at it, but it has most likely something to do with security or permissions.

If you log onto the server with the TM1 account and run RushTI through the command line, does it work?

**Comment by mandeepSin** [comment]
yes it does work if i log in using the same account.

**Comment by MariusWirtz** [comment]
That's very unusual. I don't understand why the SSO works and doesn't work for the same user.

A possible workaround, to avoid SSO altogether, would be to provide user, password, and namespace in the config.ini.
https://code.cubewise.com/tm1py-help-content/how-to-authenticate-to-tm1-with-tm1py

To avoid the plain password in the config.ini you can also provide a b64 encoded password and add `decode_b64=True` in the config.ini

**Comment by mandeepSin** [comment]
Hi Marius, thanks for your reply.

I have been able to get around this issue by using the windows scheduler rather than calling it from a chore.

Thanks For all your help.
