### ISSUE TITLE
Aliases in the namespace Config.ini

### ISSUE THREAD

**Issue by Kisoonx** [cubewise-code/rushti#50]
It is not possible to use aliases in the namespace.
Is this a problem of rest api?

**Comment by MariusWirtz** [comment]
I'm not sure I understand. What do you mean by the alias of the namespace?
Could you please provide a sample?

**Comment by Kisoonx** [comment]
Sorry!
Aliases by settings from Cognos Analytics. 

UPD:
This is only used in Cognos Analytics, not for the REST API. 
Closing the problem.
