### ISSUE TITLE
No "chardet" module in dependencies

### ISSUE THREAD

**Issue by Kisoonx** [cubewise-code/rushti#51]
Missing chardet module in dependencies.

**Comment by MariusWirtz** [comment]
The chardet dependency is included in the requirements.txt 
**https://github.com/cubewise-code/rushti/blob/master/requirements.txt**

Do you think we should list it in the readme.md as well?

**Comment by Kisoonx** [comment]
Yes, thx

**Comment by MariusWirtz** [comment]
@cubewise-gng
Let's make `chardet` an optional dependency. If it isn't installed RushTI should skip the preprocessing of the file.

Is that OK?
