### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by Kisoonx** [cubewise-code/rushti#54]
How about an additional parameter in the tasks file for separate process logging (if error)?
This is useful for checking when processes have not completed successfully.

Tasks.txt example :
id="" predecessors="" instance="M1" process="Pro_1" logfile_if_error="C:\RushTI\TasksLogs\M1.txt"
id="" predecessors="" instance="M1" process="Pro_2" logfile_if_error="C:\RushTI\TasksLogs\M1.txt"

id="" predecessors="" instance="M1" process="Pro_3" logfile_if_error="C:\RushTI\TasksLogs\Pro_3.txt"

id="" predecessors="" instance="M999" process="Pro_AAA" logfile_if_error="C:\RushTI\TasksLogs\M999.txt"
id="" predecessors="" instance="M999" process="Pro_BBB" logfile_if_error="C:\RushTI\TasksLogs\M999.txt"
id="" predecessors="" instance="M999" process="Pro_CCC" logfile_if_error="C:\RushTI\TasksLogs\M999.txt"

**Comment by MariusWirtz** [comment]
Hi @Kisoonx,

thanks for proposing this feature.
Please provide a bit more background. Why is it beneficial to have error logs in a separate file compared to having all error logs in the main log file?

**Comment by Kisoonx** [comment]
Hi @MariusWirtz ))

Global reason> Logfiles as ERROR flag for checking after completed (using WildcardFileSearch TI-function without subprocess to read and parse MORE info in global logfile)
Other reason > When count of instance > 1, global logfile go to garbage

**Comment by MariusWirtz** [comment]
Hi @Kisoonx,

thanks!
I understand. I wonder if this is the best way to communicate errors back to TM1 though! 

Perhaps it would be nicer if RushTI creates a cube in your model (if it doesn't already exist) that has run info (completion-state, runtime, etc.) for every execution (id)
What do you think?

**Comment by Kisoonx** [comment]
Hi @MariusWirtz 

Control cube is good idea! )) But I have a little doubt about the structure of the cube.

If there were multiple calls to the same process, but with different parameter values, then it will take multiple lines (-new custom dimension in cube) of information about the same process, but with different parameter values.

In this case need to think carefully about the nuances.

**Comment by ak-cube** [comment]
Hi @MariusWirtz,
 
It would be helpful if I was able to send the log file name as a parameter. In that case, I would create log files which includes the process name and timestamp. Several log files make it easy to read, easy to  find, easy to keep the history. As well, you can read only the last line of the log file to see the execution result and write it back to TM1.

Thanks.

**Comment by MariusWirtz** [comment]
The log file is configured with the `logging_config.ini`. TBH I don't really like the idea to overrule this configuration at runtime.

If you only need to pass the state of the execution back to TM1, perhaps RushTI could optionally create a kind of result file in the current directory with a file name of your choice and a simple `true` or `false` message depending on whether it was fully successful or not.

Would that solve your requirement?

**Comment by MariusWirtz** [comment]
this will be resolved with #68
