### ISSUE TITLE
Error with reading umlauts in the parameters

### ISSUE THREAD

**Issue by ak-cube** [cubewise-code/rushti#63]
The rushti returns the error if the parameters include umlauts:

![image](https://github.com/cubewise-code/rushti/assets/104438062/97612495-fc48-415a-8ddb-122631f5fb8c)

Here is command lines for reproducing: 
`id="1" predecessors="" instance="any model name" process="Any process name" pDim="Property" pCountry="All Countries" pPartner="GEB" pManager="WARLICH"
id="2" predecessors="1" instance="any model name" process="Any process name" pDim="Property" pCountry="All Countries" pPartner="GEB" pManager="BÖNNEMANN"
id="3" predecessors="1" instance="any model name" process="Any process name" pDim="Property Lease" pCountry="All Countries" pPartner="GEB" pManager="BÖNNEMANN"
id="4" predecessors="1" instance="any model name" process="Any process name" pDim="Property Unit" pCountry="All Countries" pPartner="GEB" pManager="BÖNNEMANN"
id="5" predecessors="1" instance="any model name" process="Any process name" pDim="Property" pCountry="All Countries" pPartner="GEB" pManager="SCHÖNFELD"
id="6" predecessors="1" instance="any model name" process="Any process name" pDim="Property Lease" pCountry="All Countries" pPartner="GEB" pManager="SCHÖNFELD"
id="7" predecessors="1" instance="any model name" process="Any process name" pDim="Property Unit" pCountry="All Countries" pPartner="GEB" pManager="SCHÖNFELD"`

**Comment by MariusWirtz** [comment]
Please try again but make sure that the tasks file is encoded in UTF-8.

When the file is created with TI you can set the encoding like this:

```
SetOutputCharacterSet('tasks.txt','TM1CS_UTF8');
```
Make sure this line is included in the same code tab where the `ASCIIOUTPUT` takes place
