### ISSUE TITLE
'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by pdvanderberg** [cubewise-code/rushti#78]
I am having issues with a process that I have converted to run on Rush TI. I used the exact same process of a job that has been working successfully for the last 11 months as a base but the command I am calling is created using the exact same code as well as the output in my script file other than pointing to a different process. 

When I execute from PA it says starting but with no further entries in the log and the process stops. I have created asciiouput on both commands to manually run in cmd, the old process executes without any issues, new process returns the error that says:

> File "<frozen codecs>", line 322, in decode, UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa6 in postion 98: invalid start byte.

![image](https://github.com/cubewise-code/rushti/assets/47628384/5ee8197f-f953-481a-84ae-f2f52e5ca102)
Error in CMD

![image](https://github.com/cubewise-code/rushti/assets/47628384/fc336df8-c87b-4876-9bd3-10c66a243ac4)
New command code at the back compared to the old command in front

![image](https://github.com/cubewise-code/rushti/assets/47628384/b22a5003-cd6d-4d22-8316-a8d747e784e6)
Task script files, new file in front, old file in back.

![image](https://github.com/cubewise-code/rushti/assets/47628384/2e66d912-aa3f-486a-894b-b33e0d817bd5)
RushTI log file

Running it in TM1py 2.0

**Comment by MariusWirtz** [comment]
please try this
https://github.com/cubewise-code/rushti/issues/40#issuecomment-842162530

In https://github.com/cubewise-code/rushti/commit/f52fe0b1476e476152a63228ebc757e8e51fcc98 we also introduced a feature so that RushTI converts the file autonomously.
However, it requires an optional dependency: chardet.

If chardet is installed, RushTI should be fine to consume non-utf-8 files.

**Comment by pdvanderberg** [comment]
Hi Marius, 

We do have Chardet installed 

![image](https://github.com/cubewise-code/rushti/assets/47628384/0c50b1ae-de44-46bd-9a72-d50adc3969f4)

I have played around further with the file output and the character causing the issue was "¦" after removing it it resolved the issue.
