### ISSUE TITLE
Allow RushTI to ignore minor errors on OPT task type

### ISSUE THREAD

**Issue by nicolasbisurgi** [cubewise-code/rushti#86]
Hi,
Currently RushTI has a binary behavior when it comes to return codes. If all processes finish successfully then it returns 0, if any process fails (for whatever reason) it return a non-zero value.
It would be great to introduce a flag per task that allows processes that end with `HasMinorErrors` to be considered successful (i.e.: to give a returnCode of 0).
Though it's a TI responsibility to handle possible minor errors, there could be times where this is not either possible or even followed. 

This parameter must OPTIONAL and, IMHO, should only be applicable to OptimizedTasks as they are the ones that you would use when you want to have more precise control on the outcome of the TI processes invoked by RushTI.

It would look like this:
`id="1" predecessors="" require_predecessor_success="" succeed_on_minor_errors="1" instance="tm1srv01" process="export.actuals" pMonth=Jan`

Thoughts?

**Comment by MariusWirtz** [comment]
Yes. This makes sense
