### ISSUE TITLE
Return Code

### ISSUE THREAD

**Issue by ottaviopf** [cubewise-code/rushti#9]
Is it possible to implement the functionality to return errorcode from RushTI?
It will be very helpfull when triggered from a cmd file or a scheduler.
Thank you!

**Comment by MariusWirtz** [comment]
Hi @ottaviopf,
Nice idea! thanks for the contribution!

I implemented the feature in this [branch](https://github.com/cubewise-code/rushti/tree/issue/9-return-code)
Can you please check if it works for you? Beware, it requires [TM1 11.3 IF 1 or higher](https://github.com/cubewise-code/tm1py/issues/65).
